[package]
name = "dec64"
version = "0.1.0"
authors = ["Maciej Hirsz <maciej.hirsz@gmail.com>"]
description = "DEC64 implementation in Rust"
repository = "https://github.com/maciejhirsz/DEC64"
license = "MIT"
